import { MAX_PLAYERS } from './types'

const ADJECTIVES = [
  'Swift', 'Turbo', 'Blocky', 'Neon', 'Rapid', 'Jumpy', 'Cosmic', 'Wild',
  'Iron', 'Shadow', 'Pixel', 'Rocket', 'Thunder', 'Zippy', 'Mega', 'Lucky',
]

const NOUNS = [
  'Fox', 'Tiger', 'Falcon', 'Panda', 'Shark', 'Comet', 'Bolt', 'Yak',
  'Otter', 'Raven', 'Puma', 'Gecko', 'Moose', 'Hawk', 'Cobra', 'Bison',
]

export interface Outfit {
  name: string
  shirt: string
  pants: string
  chip: string
}

/**
 * One distinct outfit per player slot. The first five are hand-picked because
 * most races are small; beyond that they are generated by walking the hue
 * circle in big steps, so neighbouring slots never get similar colours.
 */
const HAND_PICKED: Outfit[] = [
  { name: 'Red', shirt: '#e8503a', pants: '#2f4a7a', chip: '#ff7a63' },
  { name: 'Cyan', shirt: '#2fb8c6', pants: '#1f3b57', chip: '#56e0ec' },
  { name: 'Lime', shirt: '#7cc23d', pants: '#3b4a22', chip: '#a6e86a' },
  { name: 'Violet', shirt: '#9b59d0', pants: '#3a2a59', chip: '#c08cf0' },
  { name: 'Amber', shirt: '#eaa32b', pants: '#5a3a16', chip: '#ffc45f' },
]

/** Golden-angle hue steps keep generated colours far apart from each other. */
const HUE_STEP = 137.508

function hsl(h: number, s: number, l: number): string {
  return `hsl(${((h % 360) + 360) % 360}, ${s}%, ${l}%)`
}

function generatedOutfit(slot: number): Outfit {
  const hue = (slot - HAND_PICKED.length + 1) * HUE_STEP + 20
  return {
    name: `Runner ${slot + 1}`,
    shirt: hsl(hue, 62, 55),
    pants: hsl(hue + 18, 35, 28),
    chip: hsl(hue, 78, 68),
  }
}

export const OUTFITS: Outfit[] = Array.from({ length: MAX_PLAYERS }, (_, slot) =>
  slot < HAND_PICKED.length ? HAND_PICKED[slot] : generatedOutfit(slot),
)

export function randomName(): string {
  const a = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)]
  const n = NOUNS[Math.floor(Math.random() * NOUNS.length)]
  return `${a}${n}`
}

/** Random client id, also used for deterministic slot ordering and host election. */
export function randomId(): string {
  return Math.random().toString(36).slice(2, 10) + Date.now().toString(36).slice(-4)
}

const CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789' // no I/O/0/1 - easy to read out loud

export function randomRoomCode(length = 5): string {
  let code = ''
  for (let i = 0; i < length; i++) {
    code += CODE_ALPHABET[Math.floor(Math.random() * CODE_ALPHABET.length)]
  }
  return code
}

export function normalizeRoomCode(input: string): string {
  return input.trim().toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 8)
}

export function outfitForSlot(slot: number): Outfit {
  return OUTFITS[((slot % OUTFITS.length) + OUTFITS.length) % OUTFITS.length]
}
